# Generated by Django 5.2.7 on 2025-10-20 15:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StringAnalysisResult',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('value', models.TextField()),
                ('components', models.JSONField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
